name: Tests conda
on: [push]

jobs:
  build:
    strategy:
      max-parallel: 6
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.7, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: defaults, anaconda, conda-forge
          environment-file: environment-ci.yml
          activate-environment: gym_anm-dev
      - name: Install from source
        shell: pwsh
        run: pip install .
      - name: Install testing dependencies
        shell: pwsh
        run: pip install coverage
      - name: Test with unittests
        shell: pwsh
        run: coverage run -m tests
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
